# Tensor 연습 문제 초급

In [1]:
import torch

In [9]:
'''
[1번]
아래 세 리스트 a, b, c를 이용해 이를 pytorch의 float64 type의 tensor로 바꾸고 그것의 크기를 print해 보세요
'''
a = [8, 6, 1]
b = [[1,7,4], [7,2,7]]
c = [[[1,2,3], [4,5,1],[9,8,2]], [[10,6,5], [2,2,7],[6,6,1]]]

# 아래에 풀이 적기
a = torch.tensor(a).to(torch.float64)
b = torch.tensor(b).to(torch.float64)
c = torch.tensor(c).to(torch.float64)

a.shape, b.shape, c.shape

(torch.Size([3]), torch.Size([2, 3]), torch.Size([2, 3, 3]))

In [10]:
'''
[2번]
아래 두 tensor a와 b의 합을 구하고 그 결과를 출력하세요
'''

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 아래에 풀이 적기
a.add(b)

tensor([5, 7, 9])

In [11]:
'''
[3번]
아래 tensor의 최솟값과 최댓값을 출력해세요
'''
a = torch.tensor([2, 4, 1, 7, 5])

# 아래에 풀이 적기
a.min(), a.max()

(tensor(1), tensor(7))

In [14]:
'''
[4번]
모든 값이 0으로 채워진 3 x 4 tensor a를 만드세요
'''

# 아래에 풀이 적기
a = torch.zeros(3, 4)
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
'''
[5번]
3 이상 10 이하의 정수로 이루어진 3 x 4 크기의 tensor a를 만드세요
'''

# 아래에 풀이 적기
a = torch.randint(3, 11, (3, 4))
a

tensor([[ 8,  3,  9,  9],
        [ 4,  3,  7, 10],
        [10,  6,  8,  5]])

In [19]:
'''
[6번]
아래 a tensor의 앞에서부터 2번 째 원소와 가장 마지막 원소를 출력하세요
'''
a = torch.tensor([2, 4, 5, 7, 5])

# 아래에 풀이 적기
a[1], a[-1]

(tensor(4), tensor(5))

In [21]:
'''
[7번]
아래 a tensor의 크기를 출력하고
이를 3 x 2 x 2 크기를 갖는 b tensor로 변경해보세요
'''
a = torch.randn((2, 6))

# 아래에 풀이 적기
print(a.shape)
b = a.reshape((3, 2, 2))
b

torch.Size([2, 6])


tensor([[[ 0.9127, -0.5291],
         [ 0.0148,  1.4374]],

        [[-0.9480, -0.1738],
         [ 0.3073, -0.3343]],

        [[ 1.7797, -0.9913],
         [-0.2630, -0.8207]]])

In [24]:
'''
[8번]
아래 a tensor의 모든 원소의 값을 3배 해 보세요
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기
a.mul(3)

tensor([ 3,  6,  9, 12])

In [25]:
'''
[9번]
아래 a tensor의 모든 원소의 값을 제곱 해 보세요
'''
a = torch.tensor([1, 2, 3, 4])

# 아래에 풀이 적기
a ** 2

tensor([ 1,  4,  9, 16])

# Tensor 연습 문제 중급

In [34]:
'''
[1번]
아래 a tensor를 첫 번째 차원을 기준으로 합을 구하세요
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# 아래에 풀이 적기
torch.sum(a, dim=0), torch.sum(a, dim=1), torch.sum(a, dim=2)

(tensor([[ 2,  4,  6],
         [ 8, 10, 12]]),
 tensor([[5, 7, 9],
         [5, 7, 9]]),
 tensor([[ 6, 15],
         [ 6, 15]]))

In [38]:
'''
[2번]
아래 a tensor에서 5보다 작은 원소만 출력해보세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기
a < 5, a[a < 5]

(tensor([ True,  True, False,  True, False,  True, False,  True, False, False]),
 tensor([0, 1, 2, 3, 4]))

In [42]:
'''
[3번]
아래 a tensor에서 짝수번째 원소만 출력해보세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기
a[1::2] # 시작인덱스::간격

tensor([1, 2, 3, 4, 5])

In [51]:
'''
[4번]
아래 a tensor의 원소를 반대의 순서로 갖는 tensor b를 만드세요
'''
a = torch.tensor([0, 1, 9, 2, 8, 3, 7, 4, 6, 5])

# 아래에 풀이 적기
b = torch.flip(a, dims=[0])
b

tensor([5, 6, 4, 7, 3, 8, 2, 9, 1, 0])

In [52]:
'''
[5번]
아래 a tensor를 모든 차원에 대해 최소값과 최대값을 구하세요.
'''
a = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

# 아래에 풀이 적기
torch.min(a), torch.max(a)

(tensor(1), tensor(9))

In [54]:
'''
[6번]
아래 a tensor의 짝수 행은 모두 0으로 홀수 행은 모두 1로 바꾸세요
'''
a = torch.tensor(
    [
        [0, 0, 0], # 1번째 행
        [1, 1, 1], # 2번째 행
        [2, 2, 2], # 3번째 행
        [3, 3, 3], # 4번째 행
        [4, 4, 4], # 5번째 행
        [5, 5, 5], # 6번째 행
        [6, 6, 6], # 7번째 행
        [7, 7, 7], # 8번째 행
        [8, 8, 8], # 9번째 행
        [9, 9, 9], # 10번째 행
    ]
)

# 아래에 풀이 적기
a[0::2] = 1
a[1::2] = 0
a

tensor([[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]])

In [55]:
'''
[7번]
아래 a tensor의 짝수 열은 모두 0으로 홀수 열은 모두 1로 바꾸세요
'''
a = torch.tensor(
    [
        [0,    0,    0],
        [1,    1,    1],
        [2,    2,    2],
        [3,    3,    3],
        [4,    4,    4],
        [5,    5,    5],
        [6,    6,    6],
        [7,    7,    7],
        [8,    8,    8],
        [9,    9,    9],
    ] # 1열  2열    3열
)

# 아래에 풀이 적기
a[:, 0::2] = 1
a[:, 1::2] = 0
a

tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])

In [56]:
'''
[8번]
아래 a tensor를 오름차순과 내림차순으로 정렬해보세요

'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기
torch.sort(a, descending=False), torch.sort(a, descending=True)

(torch.return_types.sort(
 values=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 indices=tensor([9, 4, 8, 2, 6, 1, 5, 7, 3, 0])),
 torch.return_types.sort(
 values=tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 indices=tensor([0, 3, 7, 5, 1, 6, 2, 8, 4, 9])))

# Tensor 연습 문제 고급

In [57]:
'''
[1번]
아래 a tensor에서 0.3 보다 큰 값의 수를 출력해 보세요
'''
a = torch.randn((2,5,3))

# 아래에 풀이 적기
a[a > 0.3]

tensor([0.9491, 0.6835, 1.1837, 0.7161, 0.4126, 0.4049, 0.4307, 0.4289, 0.3487])

In [58]:
'''
[2번]
아래 a tensor에서 음수는 모두 0으로 바꾸세요
'''
a = torch.tensor(
    [
        [-2, -1,  2,  5],
        [ 1,  1, -1,  0],
        [ 2, -1, -1, -1],
        [-1, -1, -1,  3],
        [ 0, -1,  1,  2],
        [ 1, -1,  1, -1],
    ]
)

# 아래에 풀이 적기
a[a < 0] = 0
a

tensor([[0, 0, 2, 5],
        [1, 1, 0, 0],
        [2, 0, 0, 0],
        [0, 0, 0, 3],
        [0, 0, 1, 2],
        [1, 0, 1, 0]])

In [63]:
'''
[3번]
아래 a tensor를 sigmoid 함수를 적용시켜보세요
sigmoid 함수 : 1 / (1 + e^(-x))
그리고 torch.sigmoid(a)의 결과와 비교해 보세요
'''
a = torch.tensor([1, 3, 5])

# 아래에 풀이 적기
def my_sigmoid(x: torch.tensor):
  return 1 / (1 + torch.exp(-x))

my_sigmoid(a), my_sigmoid(a) == torch.sigmoid(a)

(tensor([0.7311, 0.9526, 0.9933]), tensor([True, True, True]))

In [65]:
'''
[4번]
아래 a tensor를 평균이 0 표준편차가 1이 되도록 정규화 코드를 작성하세요
'''
a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# 아래에 풀이 적기
mean = a.mean()
std = a.std()
norm = (a - mean) / std
norm

tensor([-1.2649, -0.6325,  0.0000,  0.6325,  1.2649])

In [69]:
'''
[5번]
아래 a tensor의 모든 원소를 오름차순으로 정렬한 후 크기 기준 상위 10%의 원소만 출력해보세요
'''
a = torch.tensor([9, 5, 3, 8, 1, 6, 4, 7, 2, 0])

# 아래에 풀이 적기
length = int(len(a) * 0.1)
torch.sort(a, descending=False).values[:length]


tensor([0])

In [73]:
'''
[6번]
아래 a tensor를 1차원으로 평탄화하고, 각 원소가 몇 번 등장하는지 세어 결과를 딕셔너리로 출력하는 코드를 작성하시오
'''
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 아래에 풀이 적기
from collections import Counter
Counter(a.flatten().tolist())

Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1})

In [72]:
'''
[7번]
인덱싱과 슬라이싱을 활용해 아래 a tensor에서 [[4, 5], [7, 8]]를 출력해 보세요
'''
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 아래에 풀이 적기
a[1:][:, :2]

tensor([[4, 5],
        [7, 8]])