In [8]:
import numpy as np
import torch

In [9]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [10]:
b = torch.from_numpy(a.copy())
b

tensor([1, 2, 3, 4])

In [11]:
b[0] = 5
b

tensor([5, 2, 3, 4])

In [12]:
a

array([1, 2, 3, 4])

텐서의 생성자를 쓰는 일은 거의 없다. <br>
대신, zeros, ones_like 같은 녀석들을 사용해서 mask 같은걸 만들때 쓰곤 한다

In [13]:
a = torch.zeros((1, 2))
a

tensor([[0., 0.]])

In [14]:
b = torch.ones_like(a)
b

tensor([[1., 1.]])

In [15]:
c = torch.randn((2, 3))
c

tensor([[ 1.5812, -0.4329,  0.8651],
        [ 0.8078,  0.0381,  1.4721]])

## Tensor: inspection

생성, load, 계산 중간의 어떠한 형태의 텐서든 그 특성을 살펴봐야 할 경우가 매우 많음 <br>
특히 텐서의 크기 관련 문법을 많이 사용함

In [16]:
# 텐서 모양 확인
a = torch.randn((3, 6, 5))
a.shape

torch.Size([3, 6, 5])

In [17]:
# 텐서 차원 확인
a = torch.randn((3, 6, 5))
a.dim()

3

### Tensor: in-place 생성과 동시에 치환

In [18]:
a = torch.ones((2,3))
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
b = a.add(2)
b

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [20]:
a.add_(2)
a

tensor([[3., 3., 3.],
        [3., 3., 3.]])

### Tensor: Casting

모든 과정의 자료형이 통일되어야 연산이 진행됨을 아록 있음됨 <br>
경량화를 위한 quantization 이 아닌 이상 torch.float32 를 사용하면 됨

In [21]:
a = torch.Tensor([3])
a.dtype

torch.float32

In [22]:
a = a.to(torch.int64)
a.dtype

torch.int64

In [25]:
a = a.to('mps') # GPU로 전환. mac에선 'mps'
a.dtype

torch.int64

### Tensor: 차원 변환(1/2)

텐서의 차원 변환: reshape <br>
cf) view 는 텐서의 데이터를 바꾸지 않고 새로운 형태로 보여주기만 하는 방식으로 동작. 즉, 텐서 형태만 변경. view 를 사용하려면 원본 텐서가 연속적인 메모리 레이아웃을 가져야한다. <br>
reshape 은 텐서의 형태를 변경한다. 원본 텐서의 메모리 레이아웃이 비연속적일 경우에 reshape 은 데이터를 복사하여 새로운 텐서를 만든다. 따라서 view 가 실패할 수 있는 상황에서도 동작하지만 성능상의 오버헤드가 있을 수도 있다
=> reshape 은 contiguous 한 상태인지 보고, 필요하면 메모리를 복사한다

In [26]:
a = torch.randn((3, 6, 5)) # 3차원 텐서. 90개의 원소
a = a.reshape(-1, 3) # -1은 나머지 차원을 알아서 계산해달라
a.shape # reshape 후에도 원소의 개수는 동일

torch.Size([30, 3])

In [39]:
a = torch.randn(1,2,3,4)
b = a.transpose(1,2)
b.shape
a.is_contiguous(), b.is_contiguous() # 메모리에 연속적으로 저장되어 있는지 확인

(True, False)

In [27]:
# 차원의 값이 1인 차원 없애기 (squeeze)
# 차원의 값이 1인 차원을 추가하기 (unsqueeze)
# => 내가 원하는 차원의 개수를 만들기 위해 squeeze, unsqueeze를 사용
# => 1인 차원을 줄일때는 주의해야 함(원래 차원이 1이었는데 1인 차원을 없애면 차원이 사라짐)
a = torch.randn((3, 1, 5))
b = a.squeeze()
c = a.unsqueeze(-1)

b.shape, c.shape

(torch.Size([3, 5]), torch.Size([3, 1, 5, 1]))

### Tensor: 차원 변환(2/2)

In [28]:
# Tensor 합치기: torch.cat
a = torch.randn((3, 6, 5))
b = torch.randn((3, 1, 5))
c = torch.cat([a, b], dim=1)
c.shape

torch.Size([3, 7, 5])

In [29]:
# 새로운 차원 추가하고 합치기: torch.stack
# stack 은 새로운 차원을 만들고 나서 그 축을 기준으로 합칩
# stack = unsqueeze + cat
a = torch.randn((3, 5))
b = torch.randn((3, 5))
c = torch.stack([a, b], dim=1)
c.shape

torch.Size([3, 2, 5])

### Tensor: Indexing

In [30]:
a = torch.randn((64, 128))
b = a[1, :]
c = a[1:2, :]

# 결과가 다르다!!!
# b는 단일 행을 선택하여 1차원 텐서로 반환되고, 
# c는 슬라이싱을 사용하여 해당 행을 포함하는 2차원 텐서로 반환
b.shape, c.shape

(torch.Size([128]), torch.Size([1, 128]))